### ISSUE TITLE
i am sorry for asking, but can we please have an update?

### ISSUE THREAD

**Issue by zer0fl0w** [robcollins55/Raspberry-Pi-4-OpenWRT-Router-Custombuild#2]
hi rob,

many thanks for this build.

i know it is rude to ask for eta, so pardon me.

unfortunately the problem with luci is now not rare anymore. it happens every reboot.
a little bit pain always. the workaround with the luci-reinstall is not working anymore.
there is a kernel-mismatch error message everytime.

any news would be really appreciated.

thanks in advance.

**Comment by wayover13** [comment]
I went with wulfy23's build because of LuCi not being accessible under this build. It went fairly smoothly apart from the fact that wulfy23 left a very important wifi module out of his build (kmod-mac20811--a serious oversight) as well as a module for the usb NIC I intended to use (it was a non-standard one). wulfy23 is definitely keeping up with OpenWRT development better than this project

**Comment by zer0fl0w** [comment]
thanks for the heads up. i wasnt aware of any other builds.
will check out.
